FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime

RUN apt-get update \
  # Install dependencies
  && apt-get install -y git build-essential wget curl vim ffmpeg libsm6 libxext6

ADD pyproject.toml /opt/zetta_utils/
ADD setup.cfg /opt/zetta_utils/
WORKDIR /opt/zetta_utils

RUN mkdir /opt/cue && \
    cd /opt/cue &&\
    wget https://github.com/cue-lang/cue/releases/download/v0.4.3/cue_v0.4.3_linux_amd64.tar.gz && \
    tar -xzvf cue_v0.4.3_linux_amd64.tar.gz  && \
    cp cue /bin/

RUN pip install -e '.[all]'
COPY . /opt/zetta_utils/

  # Cleanup apt
  #&& conda clean -afy \
  #&& apt-get --purge autoremove -y build-essential \
  #&& apt-get clean \
  #&& rm -rf /var/lib/apt/lists/*
