resourceLimits:
  - resourceType: 'cpu'
    maximum: 1000
  - resourceType: 'memory'
    maximum: 16000
  - resourceType: 'nvidia-tesla-t4'
    maximum: 100
  - resourceType: 'nvidia-l4'
    maximum: 100
  - resourceType: 'nvidia-tesla-a100'
    maximum: 100
  - resourceType: 'nvidia-a100-80gb'
    maximum: 100
  - resourceType: 'nvidia-h100-80gb'
    maximum: 100
  - resourceType: 'nvidia-h100-mega-80gb'
    maximum: 100

shieldedInstanceConfig:
  enableSecureBoot: false
  enableIntegrityMonitoring: true

diskSizeGb: 64

serviceAccount: "{CLUSTER_NAME}-worker@{PROJECT_NAME}.iam.gserviceaccount.com"
locations:
  - {NODE_LOCATIONS}

autoprovisioningNodePoolDefaults:
  oauthScopes:
    - https://www.googleapis.com/auth/cloud-platform
  upgradeSettings:
    maxSurge: 0
    maxUnavailable: 1
  management:
    autoUpgrade: true
    autoRepair: true
