version: '3.9'

services:
  web_api:
    image: us-east1-docker.pkg.dev/zetta-research/zutils/web_api:latest
    env_file: .env
    environment:
      - DB_HOST=host.docker.internal # for local development
    command: hypercorn app.main:app --bind 0.0.0.0:8000
    ports:
      - 8000:8000

  web_api_gpu:
    image: us-east1-docker.pkg.dev/zetta-research/zutils/web_api_gpu:latest
    env_file: .env
    environment:
      - DB_HOST=host.docker.internal # for local development
    command: hypercorn app.main:app --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
